# Generated by Django 5.0.7 on 2024-10-10 20:08

import django.db.models.deletion
import route.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[route.validators.validate_first_letter_uppercase], verbose_name='Название станции')),
                ('city', models.CharField(max_length=255, validators=[route.validators.validate_first_letter_uppercase], verbose_name='Город')),
                ('country', models.CharField(max_length=255, validators=[route.validators.validate_first_letter_uppercase], verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(validators=[route.validators.validate_date_more_than_now], verbose_name='Время отправления')),
                ('arrival_time', models.DateTimeField(validators=[route.validators.validate_date_more_than_now], verbose_name='Время прибытия')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Начальная цена')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='train.train', verbose_name='Поезд')),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_route', to='route.station', verbose_name='Откуда')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_route', to='route.station', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.IntegerField(blank=True, default=0, verbose_name='Номер остановки')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прибытия')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправления')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='route.route', verbose_name='Маршрут')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='route.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
            },
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('stop_number', 'route'), name='unique_stop_number_route'),
        ),
    ]
