# Generated by Django 5.0.7 on 2024-09-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('Плацкарт', 'Плацкарт'), ('Купе', 'Купе'), ('Сидячий', 'Сидячий')])),
                ('capacity', models.IntegerField()),
                ('seats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='train.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('Скоростной', 'Скоростной'), ('Междугородний', 'Междугородний'), ('Пригородный', 'Пригородный')])),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train', to='train.car')),
            ],
        ),
    ]
