# Generated by Django 5.0.7 on 2024-10-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('train', 'number')},
        ),
    ]
